Fixing stdin logic (use Stdin if SubdomainsList is blank)
projectdiscovery/shuffledns pull request #140
Opened 2022-07-20 19:41 UTC by mohammadanaraki

`subfinder -d example.com | shuffledns -list example-subdomains.txt -d example.com -r resolvers.txt`
I expect this command to use example-subdomains.txt but it uses STDIN(subfinder -d example.com)

2022-10-03 22:35 UTC, Mzack9999 requested changes
PR should point to `dev`

2022-10-27 17:02 UTC, Ice3man543 approved these changes

2023-05-07 11:41 UTC, ehsandeep approved these changes

2023-05-07 11:41 UTC, ehsandeep approved these changes

2023-05-07 11:41 UTC, merged